### ISSUE TITLE
[Configuration] Allow configurable color when timer is running.

### ISSUE THREAD

**Issue by JU12000** [Amin-Cheribet/pomodoro-vsc#3]
On certain color schemes the red of the timer when it is running is difficult if not impossible to see. I really like the sound features of this timer and so prefer to use it over others but am unable to see it when it's running with my preferred color scheme.

Add a way to configure the running color of the timer, or change it to a more universally visible color (e.g. use the theme default text color).

Thanks for your work on this! It's a great extension.

**Comment by Amin-Cheribet** [comment]
Hi @JU12000,
Thanks for trying to improve this project,
I will be working on this feature next week.
